[2024-10-19T21:14:04.347+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-19T21:14:04.813+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone.get_data scheduled__2024-10-18T01:00:00+00:00 [queued]>
[2024-10-19T21:14:04.994+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone.get_data scheduled__2024-10-18T01:00:00+00:00 [queued]>
[2024-10-19T21:14:05.010+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-19T21:14:06.059+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): get_data> on 2024-10-18 01:00:00+00:00
[2024-10-19T21:14:06.265+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2739) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-19T21:14:06.298+0000] {standard_task_runner.py:72} INFO - Started process 2778 to run task
[2024-10-19T21:14:06.298+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'capstone', 'get_data', 'scheduled__2024-10-18T01:00:00+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/rockets/capstone.py', '--cfg-path', '/tmp/tmp3dsztcx4']
[2024-10-19T21:14:06.309+0000] {standard_task_runner.py:105} INFO - Job 75: Subtask get_data
[2024-10-19T21:14:07.071+0000] {task_command.py:467} INFO - Running <TaskInstance: capstone.get_data scheduled__2024-10-18T01:00:00+00:00 [running]> on host 30318035dc43
[2024-10-19T21:14:09.527+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='capstone' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-18T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-18T01:00:00+00:00'
[2024-10-19T21:14:09.575+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-19T21:14:09.581+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-19T21:14:09.585+0000] {logging_mixin.py:190} INFO - Current task name:get_data state:running start_date:2024-10-19 21:14:04.827216+00:00
[2024-10-19T21:14:09.592+0000] {logging_mixin.py:190} INFO - Dag name:capstone and current dag run status:running
[2024-10-19T21:14:09.596+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-19T21:15:58.228+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/rockets/capstone.py", line 23, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/local/lib/python3.12/urllib/request.py", line 276, in urlretrieve
    raise ContentTooShortError(
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 6225589 out of 46378576 bytes>
[2024-10-19T21:16:00.619+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-19T21:16:00.740+0000] {logging_mixin.py:190} INFO - Task start:2024-10-19 21:14:04.827216+00:00 end:2024-10-19 21:15:59.926272+00:00 duration:115.099056
[2024-10-19T21:16:00.744+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): get_data> dag:<DAG: capstone> dagrun:<DagRun capstone @ 2024-10-18 01:00:00+00:00: scheduled__2024-10-18T01:00:00+00:00, state:running, queued_at: 2024-10-19 21:13:26.980663+00:00. externally triggered: False>
[2024-10-19T21:16:00.764+0000] {logging_mixin.py:190} INFO - Failure caused by <urlopen error retrieval incomplete: got only 6225589 out of 46378576 bytes>
[2024-10-19T21:16:00.807+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=capstone, task_id=get_data, run_id=scheduled__2024-10-18T01:00:00+00:00, execution_date=20241018T010000, start_date=20241019T211404, end_date=20241019T211559
[2024-10-19T21:16:02.291+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-19T21:16:02.307+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 75 for task get_data (<urlopen error retrieval incomplete: got only 6225589 out of 46378576 bytes>; 2778)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/rockets/capstone.py", line 23, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/local/lib/python3.12/urllib/request.py", line 276, in urlretrieve
    raise ContentTooShortError(
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 6225589 out of 46378576 bytes>
[2024-10-19T21:16:03.140+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-19T21:16:03.828+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
