[2024-10-19T20:33:19.014+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-19T20:33:19.042+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data manual__2024-10-19T20:33:15.653467+00:00 [queued]>
[2024-10-19T20:33:19.053+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data manual__2024-10-19T20:33:15.653467+00:00 [queued]>
[2024-10-19T20:33:19.054+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-19T20:33:19.080+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): get_data> on 2024-10-19 20:33:15.653467+00:00
[2024-10-19T20:33:19.091+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2253) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-19T20:33:19.094+0000] {standard_task_runner.py:72} INFO - Started process 2255 to run task
[2024-10-19T20:33:19.095+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'manual__2024-10-19T20:33:15.653467+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/rockets/capstone_project.py', '--cfg-path', '/tmp/tmpoimvp7ny']
[2024-10-19T20:33:19.097+0000] {standard_task_runner.py:105} INFO - Job 69: Subtask get_data
[2024-10-19T20:33:19.191+0000] {task_command.py:467} INFO - Running <TaskInstance: stocksense.get_data manual__2024-10-19T20:33:15.653467+00:00 [running]> on host 30318035dc43
[2024-10-19T20:33:19.339+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-19T20:33:15.653467+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-19T20:33:15.653467+00:00'
[2024-10-19T20:33:19.341+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-19T20:33:19.341+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-19T20:33:19.342+0000] {logging_mixin.py:190} INFO - Current task name:get_data state:running start_date:2024-10-19 20:33:19.043124+00:00
[2024-10-19T20:33:19.343+0000] {logging_mixin.py:190} INFO - Dag name:stocksense and current dag run status:running
[2024-10-19T20:33:19.343+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-19T20:33:19.344+0000] {logging_mixin.py:190} INFO - Checking if the file pageviews-20241019-200000.gz exists in the directory...
[2024-10-19T20:33:20.882+0000] {logging_mixin.py:190} INFO - Error while checking file availability: pageviews-20241019-200000.gz is not available in https://dumps.wikimedia.org/other/pageviews/2024/2024-10/
[2024-10-19T20:33:20.886+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/rockets/capstone_project.py", line 37, in _get_data
    raise FileNotFoundError(f"{file_name} is not available in {base_url}")
FileNotFoundError: pageviews-20241019-200000.gz is not available in https://dumps.wikimedia.org/other/pageviews/2024/2024-10/
[2024-10-19T20:33:20.907+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-19T20:33:20.908+0000] {logging_mixin.py:190} INFO - Task start:2024-10-19 20:33:19.043124+00:00 end:2024-10-19 20:33:20.907023+00:00 duration:1.863899
[2024-10-19T20:33:20.909+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): get_data> dag:<DAG: stocksense> dagrun:<DagRun stocksense @ 2024-10-19 20:33:15.653467+00:00: manual__2024-10-19T20:33:15.653467+00:00, state:running, queued_at: 2024-10-19 20:33:15.690401+00:00. externally triggered: True>
[2024-10-19T20:33:20.910+0000] {logging_mixin.py:190} INFO - Failure caused by pageviews-20241019-200000.gz is not available in https://dumps.wikimedia.org/other/pageviews/2024/2024-10/
[2024-10-19T20:33:20.911+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=stocksense, task_id=get_data, run_id=manual__2024-10-19T20:33:15.653467+00:00, execution_date=20241019T203315, start_date=20241019T203319, end_date=20241019T203320
[2024-10-19T20:33:20.932+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-19T20:33:20.933+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 69 for task get_data (pageviews-20241019-200000.gz is not available in https://dumps.wikimedia.org/other/pageviews/2024/2024-10/; 2255)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/rockets/capstone_project.py", line 37, in _get_data
    raise FileNotFoundError(f"{file_name} is not available in {base_url}")
FileNotFoundError: pageviews-20241019-200000.gz is not available in https://dumps.wikimedia.org/other/pageviews/2024/2024-10/
[2024-10-19T20:33:20.960+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-19T20:33:20.999+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-19T20:33:21.006+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
