[2024-10-19T20:22:58.970+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-19T20:22:59.002+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data manual__2024-10-19T20:22:53.947763+00:00 [queued]>
[2024-10-19T20:22:59.021+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data manual__2024-10-19T20:22:53.947763+00:00 [queued]>
[2024-10-19T20:22:59.021+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-19T20:22:59.047+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): get_data> on 2024-10-19 20:22:53.947763+00:00
[2024-10-19T20:22:59.060+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2114) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-19T20:22:59.062+0000] {standard_task_runner.py:72} INFO - Started process 2116 to run task
[2024-10-19T20:22:59.064+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'manual__2024-10-19T20:22:53.947763+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/rockets/capstone_project.py', '--cfg-path', '/tmp/tmpe5xzfa3q']
[2024-10-19T20:22:59.066+0000] {standard_task_runner.py:105} INFO - Job 65: Subtask get_data
[2024-10-19T20:22:59.144+0000] {task_command.py:467} INFO - Running <TaskInstance: stocksense.get_data manual__2024-10-19T20:22:53.947763+00:00 [running]> on host 30318035dc43
[2024-10-19T20:22:59.381+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-19T20:22:53.947763+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-19T20:22:53.947763+00:00'
[2024-10-19T20:22:59.384+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-19T20:22:59.386+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-19T20:22:59.387+0000] {logging_mixin.py:190} INFO - Current task name:get_data state:running start_date:2024-10-19 20:22:59.003410+00:00
[2024-10-19T20:22:59.388+0000] {logging_mixin.py:190} INFO - Dag name:stocksense and current dag run status:running
[2024-10-19T20:22:59.390+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-19T20:22:59.392+0000] {logging_mixin.py:190} INFO - Downloading data from https://dumps.wikimedia.org/other/pageviews/2024/2024-10/pageviews-20241019-200000.gz
[2024-10-19T20:23:00.151+0000] {logging_mixin.py:190} INFO - Failed to download data from https://dumps.wikimedia.org/other/pageviews/2024/2024-10/pageviews-20241019-200000.gz: HTTP Error 503: Service Temporarily Unavailable
[2024-10-19T20:23:00.152+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/rockets/capstone_project.py", line 24, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/local/lib/python3.12/urllib/request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable
[2024-10-19T20:23:00.183+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-19T20:23:00.186+0000] {logging_mixin.py:190} INFO - Task start:2024-10-19 20:22:59.003410+00:00 end:2024-10-19 20:23:00.182221+00:00 duration:1.178811
[2024-10-19T20:23:00.187+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): get_data> dag:<DAG: stocksense> dagrun:<DagRun stocksense @ 2024-10-19 20:22:53.947763+00:00: manual__2024-10-19T20:22:53.947763+00:00, state:running, queued_at: 2024-10-19 20:22:53.961990+00:00. externally triggered: True>
[2024-10-19T20:23:00.188+0000] {logging_mixin.py:190} INFO - Failure caused by HTTP Error 503: Service Temporarily Unavailable
[2024-10-19T20:23:00.189+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=stocksense, task_id=get_data, run_id=manual__2024-10-19T20:22:53.947763+00:00, execution_date=20241019T202253, start_date=20241019T202259, end_date=20241019T202300
[2024-10-19T20:23:00.214+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-19T20:23:00.216+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 65 for task get_data (HTTP Error 503: Service Temporarily Unavailable; 2116)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/rockets/capstone_project.py", line 24, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/local/lib/python3.12/urllib/request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable
[2024-10-19T20:23:00.256+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-19T20:23:00.295+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-19T20:23:00.309+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
