[2024-10-19T21:24:39.293+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-19T21:24:39.325+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone.extract_gz scheduled__2024-10-19T16:00:00+00:00 [queued]>
[2024-10-19T21:24:39.342+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone.extract_gz scheduled__2024-10-19T16:00:00+00:00 [queued]>
[2024-10-19T21:24:39.343+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-19T21:24:39.367+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): extract_gz> on 2024-10-19 16:00:00+00:00
[2024-10-19T21:24:39.381+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3042) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-19T21:24:39.384+0000] {standard_task_runner.py:72} INFO - Started process 3044 to run task
[2024-10-19T21:24:39.384+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'capstone', 'extract_gz', 'scheduled__2024-10-19T16:00:00+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/rockets/capstone.py', '--cfg-path', '/tmp/tmpsl8aeg35']
[2024-10-19T21:24:39.388+0000] {standard_task_runner.py:105} INFO - Job 119: Subtask extract_gz
[2024-10-19T21:24:39.474+0000] {task_command.py:467} INFO - Running <TaskInstance: capstone.extract_gz scheduled__2024-10-19T16:00:00+00:00 [running]> on host 30318035dc43
[2024-10-19T21:24:39.664+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='capstone' AIRFLOW_CTX_TASK_ID='extract_gz' AIRFLOW_CTX_EXECUTION_DATE='2024-10-19T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-19T16:00:00+00:00'
[2024-10-19T21:24:39.667+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-19T21:24:39.668+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-19T21:24:39.669+0000] {logging_mixin.py:190} INFO - Current task name:extract_gz state:running start_date:2024-10-19 21:24:39.326832+00:00
[2024-10-19T21:24:39.670+0000] {logging_mixin.py:190} INFO - Dag name:capstone and current dag run status:running
[2024-10-19T21:24:39.671+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-19T21:24:39.673+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-19T21:24:39.675+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'gunzip --force /tmp/wikipageviews.gz']
[2024-10-19T21:24:39.702+0000] {subprocess.py:86} INFO - Output:
[2024-10-19T21:24:39.743+0000] {subprocess.py:93} INFO - 
[2024-10-19T21:24:39.744+0000] {subprocess.py:93} INFO - gzip: /tmp/wikipageviews.gz: invalid compressed data--format violated
[2024-10-19T21:24:39.746+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-19T21:24:39.774+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-19T21:24:39.784+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-19T21:24:39.785+0000] {logging_mixin.py:190} INFO - Task start:2024-10-19 21:24:39.326832+00:00 end:2024-10-19 21:24:39.783051+00:00 duration:0.456219
[2024-10-19T21:24:39.788+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): extract_gz> dag:<DAG: capstone> dagrun:<DagRun capstone @ 2024-10-19 16:00:00+00:00: scheduled__2024-10-19T16:00:00+00:00, state:running, queued_at: 2024-10-19 21:18:07.913015+00:00. externally triggered: False>
[2024-10-19T21:24:39.789+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2024-10-19T21:24:39.791+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=capstone, task_id=extract_gz, run_id=scheduled__2024-10-19T16:00:00+00:00, execution_date=20241019T160000, start_date=20241019T212439, end_date=20241019T212439
[2024-10-19T21:24:39.826+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-19T21:24:39.828+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 119 for task extract_gz (Bash command failed. The command returned a non-zero exit code 1.; 3044)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-19T21:24:39.891+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-19T21:24:39.914+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-10-19T21:24:39.943+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-19T21:24:39.957+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
