[2024-10-19T20:26:11.678+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-19T20:26:11.701+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.extract_gz scheduled__2024-10-18T09:00:00+00:00 [queued]>
[2024-10-19T20:26:11.712+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.extract_gz scheduled__2024-10-18T09:00:00+00:00 [queued]>
[2024-10-19T20:26:11.713+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-19T20:26:11.729+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): extract_gz> on 2024-10-18 09:00:00+00:00
[2024-10-19T20:26:11.739+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2159) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-19T20:26:11.741+0000] {standard_task_runner.py:72} INFO - Started process 2161 to run task
[2024-10-19T20:26:11.742+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'extract_gz', 'scheduled__2024-10-18T09:00:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/rockets/capstone_project.py', '--cfg-path', '/tmp/tmpqrex1paz']
[2024-10-19T20:26:11.743+0000] {standard_task_runner.py:105} INFO - Job 67: Subtask extract_gz
[2024-10-19T20:26:11.818+0000] {task_command.py:467} INFO - Running <TaskInstance: stocksense.extract_gz scheduled__2024-10-18T09:00:00+00:00 [running]> on host 30318035dc43
[2024-10-19T20:26:11.965+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='extract_gz' AIRFLOW_CTX_EXECUTION_DATE='2024-10-18T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-18T09:00:00+00:00'
[2024-10-19T20:26:11.967+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-19T20:26:11.969+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-19T20:26:11.970+0000] {logging_mixin.py:190} INFO - Current task name:extract_gz state:running start_date:2024-10-19 20:26:11.702124+00:00
[2024-10-19T20:26:11.971+0000] {logging_mixin.py:190} INFO - Dag name:stocksense and current dag run status:running
[2024-10-19T20:26:11.972+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-19T20:26:11.973+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-19T20:26:11.975+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'gunzip --force /tmp/wikipageviews.gz']
[2024-10-19T20:26:11.998+0000] {subprocess.py:86} INFO - Output:
[2024-10-19T20:26:12.409+0000] {subprocess.py:93} INFO - 
[2024-10-19T20:26:12.410+0000] {subprocess.py:93} INFO - gzip: /tmp/wikipageviews.gz: invalid compressed data--format violated
[2024-10-19T20:26:12.422+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-19T20:26:12.441+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-19T20:26:12.448+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-19T20:26:12.449+0000] {logging_mixin.py:190} INFO - Task start:2024-10-19 20:26:11.702124+00:00 end:2024-10-19 20:26:12.447328+00:00 duration:0.745204
[2024-10-19T20:26:12.450+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): extract_gz> dag:<DAG: stocksense> dagrun:<DagRun stocksense @ 2024-10-18 09:00:00+00:00: scheduled__2024-10-18T09:00:00+00:00, state:running, queued_at: 2024-10-19 20:17:39.914632+00:00. externally triggered: False>
[2024-10-19T20:26:12.450+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2024-10-19T20:26:12.451+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=stocksense, task_id=extract_gz, run_id=scheduled__2024-10-18T09:00:00+00:00, execution_date=20241018T090000, start_date=20241019T202611, end_date=20241019T202612
[2024-10-19T20:26:12.482+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-19T20:26:12.485+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 67 for task extract_gz (Bash command failed. The command returned a non-zero exit code 1.; 2161)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-19T20:26:12.518+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-19T20:26:12.563+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-19T20:26:12.573+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
